Refactor GetReadinessProbe & GetLivenessProbe
Nordix/Meridio-Operator pull request #51
Opened 2021-12-16 15:49 UTC by mandydydy

2022-01-12 16:55 UTC, zolug commented on controllers/trench/ipam.go
> +					common.GetProbeCommand(true, fmt.Sprint(":%d", common.IpamPort), ""))
fmt.Sprintf

2022-01-13 10:16 UTC, LionelJouin commented
I get this error when I try to deploy a trench:
```
2022-01-13T10:06:18.872510101Z stderr F 2022-01-13T10:06:18.872Z	ERROR	controller-runtime.manager.controller.trench	Reconciler error	{"reconciler group": "meridio.nordix.org", "reconciler kind": "Trench", "name": "trench-a", "namespace": "red", "error": "decode deployment/ipam.yaml error: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field ExecAction.spec.template.spec.containers.readinessProbe.exec.command of type []string"}
```
[0.log](https://github.com/Nordix/Meridio-Operator/files/7861912/0.log)

2022-01-13 10:25 UTC, LionelJouin requested changes

2022-01-13 10:25 UTC, LionelJouin commented on deployment/ipam.yaml
> +                command:
"Command" is written 2 times

2022-01-13 10:59 UTC, LionelJouin approved these changes

2022-01-13 18:04 UTC, zolug approved these changes

2022-01-14 09:43 UTC, merged